-- Run in Supabase SQL Editor once.
create table if not exists public.ideas (
  id text primary key,
  date date not null,
  title text not null,
  category text,
  time text,
  location text,
  description text,
  price text,
  url text,
  created_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  idea_id text not null,
  user_name text not null,
  created_at timestamptz not null default now(),
  unique (idea_id, user_name)
);

alter table public.ideas enable row level security;
alter table public.votes enable row level security;

create policy "ideas readable by everyone" on public.ideas for select using (true);
create policy "ideas insertable by everyone" on public.ideas for insert with check (true);
create policy "votes readable by everyone" on public.votes for select using (true);
create policy "votes insertable by everyone" on public.votes for insert with check (true);
create policy "votes deletable by everyone" on public.votes for delete using (true);
