-- Lisbon with Friends · shared Supabase setup
-- Run this whole script in Supabase SQL Editor. It is safe to run again.

create table if not exists public.ideas (
  id text primary key,
  date date not null,
  title text not null,
  type text not null default 'idea',
  category text,
  time text,
  start_time text,
  end_time text,
  end_date date,
  all_day boolean not null default false,
  repeat text not null default 'none',
  repeat_until date,
  location text,
  description text,
  price text,
  url text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ideas add column if not exists type text not null default 'idea';
alter table public.ideas add column if not exists start_time text;
alter table public.ideas add column if not exists end_time text;
alter table public.ideas add column if not exists end_date date;
alter table public.ideas add column if not exists all_day boolean not null default false;
alter table public.ideas add column if not exists repeat text not null default 'none';
alter table public.ideas add column if not exists repeat_until date;
alter table public.ideas add column if not exists updated_at timestamptz not null default now();

-- Shared trip profiles. Entering the same name on another device reuses the same profile.
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  name_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Votes: entry_id is the canonical link to the trip entry.
-- idea_id is retained for backward compatibility with earlier app versions.
create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  entry_id text not null,
  idea_id text,
  user_name text,
  user_id uuid,
  created_at timestamptz not null default now()
);

-- Upgrade older votes tables safely.
alter table public.votes add column if not exists entry_id text;
alter table public.votes add column if not exists idea_id text;
alter table public.votes add column if not exists user_name text;
alter table public.votes add column if not exists user_id uuid;
alter table public.votes add column if not exists created_at timestamptz not null default now();

-- Keep entry_id and idea_id synchronized for legacy rows.
update public.votes set entry_id = idea_id where entry_id is null and idea_id is not null;
update public.votes set idea_id = entry_id where idea_id is null and entry_id is not null;

-- Duplicate protection by entry + user.
create unique index if not exists votes_entry_user_name_unique
  on public.votes (entry_id,user_name)
  where entry_id is not null and user_name is not null;
create unique index if not exists votes_entry_user_id_unique
  on public.votes (entry_id,user_id)
  where entry_id is not null and user_id is not null;

create table if not exists public.entry_images (
  entry_id text primary key,
  image_url text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_splits (
  entry_id text primary key,
  enabled boolean not null default false,
  amount numeric,
  currency text default 'EUR',
  people integer default 4,
  updated_at timestamptz not null default now()
);

-- Web Push subscriptions are private server-side data. Browser clients can only
-- register/unregister their own endpoint through the security-definer RPCs below.
create table if not exists public.push_subscriptions (
  endpoint text primary key,
  p256dh text not null,
  auth text not null,
  user_id uuid,
  user_name text,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.register_push_subscription(
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_id uuid default null,
  p_user_name text default null,
  p_user_agent text default null
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.push_subscriptions(endpoint,p256dh,auth,user_id,user_name,user_agent,updated_at)
  values (p_endpoint,p_p256dh,p_auth,p_user_id,p_user_name,p_user_agent,now())
  on conflict (endpoint) do update set
    p256dh = excluded.p256dh,
    auth = excluded.auth,
    user_id = excluded.user_id,
    user_name = excluded.user_name,
    user_agent = excluded.user_agent,
    updated_at = now();
end;
$$;

create or replace function public.unregister_push_subscription(p_endpoint text)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.push_subscriptions where endpoint = p_endpoint;
$$;

revoke all on table public.push_subscriptions from anon, authenticated;
grant execute on function public.register_push_subscription(text,text,text,uuid,text,text) to anon, authenticated;
grant execute on function public.unregister_push_subscription(text) to anon, authenticated;

alter table public.ideas enable row level security;
alter table public.users enable row level security;
alter table public.votes enable row level security;
alter table public.entry_images enable row level security;
alter table public.payment_splits enable row level security;
alter table public.push_subscriptions enable row level security;

grant select, insert, update, delete on public.ideas to anon, authenticated;
grant select, insert, update on public.users to anon, authenticated;
grant select, insert, update, delete on public.votes to anon, authenticated;
grant select, insert, update, delete on public.entry_images to anon, authenticated;
grant select, insert, update, delete on public.payment_splits to anon, authenticated;

drop policy if exists "ideas readable by everyone" on public.ideas;
drop policy if exists "ideas insertable by everyone" on public.ideas;
drop policy if exists "ideas updateable by everyone" on public.ideas;
drop policy if exists "ideas deletable by everyone" on public.ideas;
drop policy if exists "users readable by everyone" on public.users;
drop policy if exists "users insertable by everyone" on public.users;
drop policy if exists "users updateable by everyone" on public.users;
drop policy if exists "votes readable by everyone" on public.votes;
drop policy if exists "votes insertable by everyone" on public.votes;
drop policy if exists "votes deletable by everyone" on public.votes;
drop policy if exists "entry images readable by everyone" on public.entry_images;
drop policy if exists "entry images insertable by everyone" on public.entry_images;
drop policy if exists "entry images updateable by everyone" on public.entry_images;
drop policy if exists "entry images deletable by everyone" on public.entry_images;
drop policy if exists "payment splits readable by everyone" on public.payment_splits;
drop policy if exists "payment splits insertable by everyone" on public.payment_splits;
drop policy if exists "payment splits updateable by everyone" on public.payment_splits;
drop policy if exists "payment splits deletable by everyone" on public.payment_splits;

create policy "ideas readable by everyone" on public.ideas for select to anon, authenticated using (true);
create policy "ideas insertable by everyone" on public.ideas for insert to anon, authenticated with check (true);
create policy "ideas updateable by everyone" on public.ideas for update to anon, authenticated using (true) with check (true);
create policy "ideas deletable by everyone" on public.ideas for delete to anon, authenticated using (true);
create policy "users readable by everyone" on public.users for select to anon, authenticated using (true);
create policy "users insertable by everyone" on public.users for insert to anon, authenticated with check (true);
create policy "users updateable by everyone" on public.users for update to anon, authenticated using (true) with check (true);
create policy "votes readable by everyone" on public.votes for select to anon, authenticated using (true);
create policy "votes insertable by everyone" on public.votes for insert to anon, authenticated with check (true);
create policy "votes deletable by everyone" on public.votes for delete to anon, authenticated using (true);
create policy "entry images readable by everyone" on public.entry_images for select to anon, authenticated using (true);
create policy "entry images insertable by everyone" on public.entry_images for insert to anon, authenticated with check (true);
create policy "entry images updateable by everyone" on public.entry_images for update to anon, authenticated using (true) with check (true);
create policy "entry images deletable by everyone" on public.entry_images for delete to anon, authenticated using (true);
create policy "payment splits readable by everyone" on public.payment_splits for select to anon, authenticated using (true);
create policy "payment splits insertable by everyone" on public.payment_splits for insert to anon, authenticated with check (true);
create policy "payment splits updateable by everyone" on public.payment_splits for update to anon, authenticated using (true) with check (true);
create policy "payment splits deletable by everyone" on public.payment_splits for delete to anon, authenticated using (true);

insert into storage.buckets (id, name, public) values ('entry-images','entry-images',true)
on conflict (id) do update set public=true;
drop policy if exists "entry images storage select" on storage.objects;
drop policy if exists "entry images storage upload" on storage.objects;
drop policy if exists "entry images storage update" on storage.objects;
drop policy if exists "entry images storage delete" on storage.objects;
create policy "entry images storage select" on storage.objects for select to anon, authenticated using (bucket_id='entry-images');
create policy "entry images storage upload" on storage.objects for insert to anon, authenticated with check (bucket_id='entry-images');
create policy "entry images storage update" on storage.objects for update to anon, authenticated using (bucket_id='entry-images') with check (bucket_id='entry-images');
create policy "entry images storage delete" on storage.objects for delete to anon, authenticated using (bucket_id='entry-images');

notify pgrst, 'reload schema';
