-- Lisbon with Friends · shared Supabase setup
-- Run this whole script in Supabase SQL Editor. It is safe to run again.

create table if not exists public.ideas (
  id text primary key,
  date date not null,
  title text not null,
  type text not null default 'idea',
  category text,
  time text,
  start_time text,
  end_time text,
  end_date date,
  all_day boolean not null default false,
  repeat text not null default 'none',
  repeat_until date,
  location text,
  description text,
  price text,
  url text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Upgrade existing projects created with the earlier schema.
alter table public.ideas add column if not exists type text not null default 'idea';
alter table public.ideas add column if not exists start_time text;
alter table public.ideas add column if not exists end_time text;
alter table public.ideas add column if not exists end_date date;
alter table public.ideas add column if not exists all_day boolean not null default false;
alter table public.ideas add column if not exists repeat text not null default 'none';
alter table public.ideas add column if not exists repeat_until date;
alter table public.ideas add column if not exists updated_at timestamptz not null default now();

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  idea_id text not null,
  user_name text not null,
  created_at timestamptz not null default now(),
  unique (idea_id, user_name)
);

create table if not exists public.entry_images (
  entry_id text primary key,
  image_url text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_splits (
  entry_id text primary key,
  enabled boolean not null default false,
  amount numeric,
  currency text default 'EUR',
  people integer default 4,
  updated_at timestamptz not null default now()
);

alter table public.ideas enable row level security;
alter table public.votes enable row level security;
alter table public.entry_images enable row level security;
alter table public.payment_splits enable row level security;

grant select, insert, update, delete on public.ideas to anon, authenticated;
grant select, insert, update, delete on public.votes to anon, authenticated;
grant select, insert, update, delete on public.entry_images to anon, authenticated;
grant select, insert, update, delete on public.payment_splits to anon, authenticated;

drop policy if exists "ideas readable by everyone" on public.ideas;
drop policy if exists "ideas insertable by everyone" on public.ideas;
drop policy if exists "ideas updateable by everyone" on public.ideas;
drop policy if exists "ideas deletable by everyone" on public.ideas;
drop policy if exists "votes readable by everyone" on public.votes;
drop policy if exists "votes insertable by everyone" on public.votes;
drop policy if exists "votes deletable by everyone" on public.votes;
drop policy if exists "entry images readable by everyone" on public.entry_images;
drop policy if exists "entry images insertable by everyone" on public.entry_images;
drop policy if exists "entry images updateable by everyone" on public.entry_images;
drop policy if exists "entry images deletable by everyone" on public.entry_images;
drop policy if exists "payment splits readable by everyone" on public.payment_splits;
drop policy if exists "payment splits insertable by everyone" on public.payment_splits;
drop policy if exists "payment splits updateable by everyone" on public.payment_splits;
drop policy if exists "payment splits deletable by everyone" on public.payment_splits;

create policy "ideas readable by everyone" on public.ideas for select to anon, authenticated using (true);
create policy "ideas insertable by everyone" on public.ideas for insert to anon, authenticated with check (true);
create policy "ideas updateable by everyone" on public.ideas for update to anon, authenticated using (true) with check (true);
create policy "ideas deletable by everyone" on public.ideas for delete to anon, authenticated using (true);

create policy "votes readable by everyone" on public.votes for select to anon, authenticated using (true);
create policy "votes insertable by everyone" on public.votes for insert to anon, authenticated with check (true);
create policy "votes deletable by everyone" on public.votes for delete to anon, authenticated using (true);

create policy "entry images readable by everyone" on public.entry_images for select to anon, authenticated using (true);
create policy "entry images insertable by everyone" on public.entry_images for insert to anon, authenticated with check (true);
create policy "entry images updateable by everyone" on public.entry_images for update to anon, authenticated using (true) with check (true);
create policy "entry images deletable by everyone" on public.entry_images for delete to anon, authenticated using (true);

create policy "payment splits readable by everyone" on public.payment_splits for select to anon, authenticated using (true);
create policy "payment splits insertable by everyone" on public.payment_splits for insert to anon, authenticated with check (true);
create policy "payment splits updateable by everyone" on public.payment_splits for update to anon, authenticated using (true) with check (true);
create policy "payment splits deletable by everyone" on public.payment_splits for delete to anon, authenticated using (true);

insert into storage.buckets (id, name, public)
values ('entry-images', 'entry-images', true)
on conflict (id) do update set public = true;

drop policy if exists "entry images storage select" on storage.objects;
drop policy if exists "entry images storage upload" on storage.objects;
drop policy if exists "entry images storage update" on storage.objects;
drop policy if exists "entry images storage delete" on storage.objects;

create policy "entry images storage select"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'entry-images');

create policy "entry images storage upload"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'entry-images');

create policy "entry images storage update"
on storage.objects for update
to anon, authenticated
using (bucket_id = 'entry-images')
with check (bucket_id = 'entry-images');

create policy "entry images storage delete"
on storage.objects for delete
to anon, authenticated
using (bucket_id = 'entry-images');
